### ISSUE TITLE
NullPointerException when trying to run LiftSession.destroySession with mock req instance in comet

### ISSUE THREAD

**Issue by Shadowfiend** [lift/framework#1145]
Lift throws a NullPointerException when attempting to run destroySession from a mock req instance with a LiftSession stub, as when trying to run:

for (liftSession <- S.session) {
  liftSession.destroySession
}

See https://groups.google.com/d/msg/liftweb/-/xOauoxgBzmUJ for discussion.

**Comment by farmdawgnation** [comment]
Stealing this since it seems like an easy win.
