### ISSUE TITLE
Add CssSelector transform to match on attribute with given name

### ISSUE THREAD

**Issue by andreak** [lift/framework#1329]
Suggested syntax for matching on the "style"-attribute and setting all styles:

"[style]" #> "border: 1px solid red"

**Comment by Shadowfiend** [comment]
So given the latest update it sounds like we probably don't really need this, right?

**Comment by andreak** [comment]
How youd you match all attributes matching a given value?

**Comment by Shadowfiend** [comment]
Do you mean something like “for all elements with any attribute set to 'hello', do something”? If so, that doesn't seem to be what this thread was about. If you mean selecting all elements whose attribute A is set to value Y, `A=Y` does that (without square brackets, in a slight departure from CSS).

My understanding was this thread was about setting all elements' `style` attribute to a given value, and that this was solved by the last example you posted of `* [style] #> "border: 1px solid red"`.

It's entirely possible I'm still confused about the particular functionality we're talking about though :)

**Comment by Shadowfiend** [comment]
I'm going to close this... It looks like *setting* an attribute is handled by the syntax:

```scala
  "* [attribute]" #> "value"
```

And *selecting by an attribute value* is handled by the syntax:

```scala
  "attribute=expected *" #> "new content"
```

If we're looking for something else, let's file a separate issue with a clear example of input/expected output/maybe a speculative syntax for the selector transform that we can discuss.
