### ISSUE TITLE
Improved checking when deserializing an Option[T]

### ISSUE THREAD

**Issue by jeppenejsum** [lift/framework#1425]
Details https://groups.google.com/d/msg/liftweb/5nMZ9hHv9Uk/Y0odnMGMJUsJ

**Comment by farmdawgnation** [comment]
@Shadowfiend unless you really want to tackle this, I think I know what's causing it from my poking around `lift-json`.

**Comment by farmdawgnation** [comment]
May steal it.

**Comment by Shadowfiend** [comment]
:thumbsup:
