### ISSUE TITLE
Call validate on BsonRecordListField elements

### ISSUE THREAD

**Issue by eltimn** [lift/framework#1587]
> When validate is called on a Record it recursively calls validate on each field. However, if a field is a list like BsonRecordListField then it does not have any validations registered by default which leads to elements of a list not being validated when validate is called from parent scope.
> 
> It's not difficult to override validations on a list field to map over all elements to get truly complete validation. I wonder though if that behaviour is by design or is it a bug? To me it seems more natural to validate all fields and their elements (list elems in this case).

https://groups.google.com/d/msg/liftweb/gh2syNeGWyw/OC3y2TLWfAkJ

**Comment by Bhashit** [comment]
Is this [already done](https://github.com/lift/framework/blob/d2b0c6b5d46259740f79f733f6088bf2b0b43be2/persistence/mongodb-record/src/main/scala/net/liftweb/mongodb/record/field/BsonRecordField.scala#L95)?

**Comment by eltimn** [comment]
It appears so: 4e4850efed5ec41d057f1afd18a81a7aa1dcac55

I'll close this then.
