### ISSUE TITLE
We don't indicate any sort of error if you make an AJAX request to an endpoint requiring JSON with invalid JSON

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1615]
We ran into an annoying edge case in how we handle JSON AJAX requests.

We were using `SHtml.jsonCall` to wire up some stuff on the client to the server. This is all fine and dandy until you submit something that doesn't result in proper JSON to the function name. No error whatsoever is generated on the server or the client.

That... should probably be fixed.

**Comment by farmdawgnation** [comment]
I'm inclined to log something on the server, to be honest. I'm concerned about surfacing the fact that something like this is happening in the application to a (potentially untrusted) end user...

**Comment by Shadowfiend** [comment]
As I think about this more, I think there should be an overload of `jsonCall` that takes a `(String)=>JsCmd` for when we couldn't parse the JSON, and the default can log on the server and no-op to the client… Then at call-time you can decide what you want to do with parse errors.

**Comment by farmdawgnation** [comment]
> I think there should be an overload of jsonCall that takes a (String)=>JsCmd

This is `SHtml.ajaxCall`...

**Comment by farmdawgnation** [comment]
Ohhhhhhhhhh. Wait wait wait, are you saying an overload of `jsonCall` that takes *both* a `(JValue)=>JsCmd` **and** a `(String)=>JsCmd`?

**Comment by Shadowfiend** [comment]
Yep, that's what I was talking about :)

**Comment by farmdawgnation** [comment]
Hokayyyyyyyyy!
