### ISSUE TITLE
Lift JSON 2.6-RC1 parser breaks with Java 8

### ISSUE THREAD

**Issue by csaltos** [lift/framework#1632]
We try to migrate from Java 7 to Java 8, but we get a very estrange ScalaSigParserError at the servers.

I tried to isolate the error at:

https://github.com/listatree/lift-json-java8

But it only breaks sometimes (in our servers breaks all the time).

An stacktrace error from our servers (not from the running tests) is at:
https://github.com/listatree/lift-json-java8/blob/master/stacktrace.txt

Notice the "net.liftweb.json.MappingException: unknown error" and the "scala.tools.scalap.scalax.rules.ScalaSigParserError: Unexpected failure"

By the way with java 8 at Mac OS X is running OK, the error is with java 8 at Debian GNU/Linux 7.7.

The exact versions:

Java 8u25 (server version for Linux 64 bits)
Debian GNU/Linux 7.7
Scala 2.11.2
Lift JSON 2.6-RC1

JVM startup parameters: -Xms3072m -Xmx3072m -server -Xss8m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=30

Since it's working on Java 7 we are delaying the migration until we can clear this bug.

Thank you very much for Lift, it's an amazing piece of software !! (Y) :)

**Comment by marekzebrowski** [comment]
java 1.8.0_31 still has that problem

**Comment by jpswain** [comment]
This page shows where it has been fixed:
https://bugs.openjdk.java.net/browse/JDK-8058847
