### ISSUE TITLE
Split LiftSession into multiple source files

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1641]
The LiftSession source is current 3,281 lines long. Notably the LiftSession implementation alone is > 2k lines, so this is probably something we could split up into different traits to make it a bit easier to grok.

**Comment by farmdawgnation** [comment]
We're already late in the Milestone cycle for 3.0 and I don't feel comfortable doing such a big refactor at this point. I vote we punt until 3.1.

**Comment by fmpwizard** [comment]
Sounds good

**Comment by dpp** [comment]
FWIW... when we split Helpers to multiple files/traits it was a huge disaster. People use some but not all the traits. Navigating the traits is a pain rather than searching for a function in a file (less of an issue with an IDE). There were all forms of problems with inner classes.

I'd vote :-1: on splitting LiftSession.

**Comment by farmdawgnation** [comment]
I think given the feedback on this I've come to the following conclusion.

First, I think we have places in `LiftSession` where the semantic coupling that's in place just doesn't make sense. I'd argue that splitting `LiftSession` wouldn't be the same as splitting `Helpers` because Helpers was and is kind of a catch-all semantically speaking.

Second, I think I've decided doing this work doesn't make sense as a discrete unit of work. I've come to the opinion that we'll deliver better results by separating these out _when_ that semantic coupling itself becomes problematic or awkward for some other goal we're trying to achieve. This ticket was refactoring for refactoring's own sake in some ways - which can have its virtues, but I'm less convinced the payoff is there than I was when I opened the ticket.

I'm going to close this for now, but if there's disagreement on this point we can have a discussion on the ML and reopen later.

**Comment by Shadowfiend** [comment]
:100: from me on the conclusion. Targeted, opportunistic refactoring of bad coupling will reap a lot of rewards… As you mentioned, much of `LiftSession` is a tangle of bad coupling, and we've already taken some swipes at it. I'll be taking some more as I continue working on refactoring snippet handling (for #1799 and friends).
