### ISSUE TITLE
LAFuture.collect / LAFuture.collectAll with empty list parameter is never satified

### ISSUE THREAD

**Issue by arkadius** [lift/framework#1653]
Hi,

One of the usages of collect/collectAll is to pass a sequence using sequence-to-vararg conversion e.g. LAFuture.collect(seqOfFutures: _*). In the corner case the seqOfFutures could be an empty list. In this case collect/collectAll is never satisfied, because f.foreach will never execute given function.

I've prepared PR reproducing problem and fixing it: #1654.

ML discussion @ https://groups.google.com/forum/#!topic/liftweb/rsscoZ2BEYM

**Comment by Shadowfiend** [comment]
As per our [contributing guidelines](https://github.com/lift/framework/blob/master/CONTRIBUTING.md) we ask that non-committers start a thread on the [mailing list](https://groups.google.com/forum/#!forum/liftweb) before opening tickets. If you can open up a thread we can confirm the issue and ask for the PR. :)

**Comment by arkadius** [comment]
Yes, but also according to guideline "We will accept pull requests represents (...) Small changes, enhancements, or bug fixes to Lift’s code", but sure I can start a thread on mailing list.

**Comment by Shadowfiend** [comment]
Yep, and I think it's likely we'll be able to accept this PR :) If you look at the bullet above it, it explicitly mentions that the PR needs to be related to an issue discussed on the mailing list beforehand; I'll update the contribution guidelines to make it clear that a PR must meet *all* of the listed criteria.

**Comment by arkadius** [comment]
I was thinking that the only one of this criteria was needed. Sorry for my misunderstanding :)

**Comment by Shadowfiend** [comment]
On the contrary, thanks for making it clear what the misunderstanding was so we could fix it!
