### ISSUE TITLE
CombParserHelpersSpec fails when string with \n is probed

### ISSUE THREAD

**Issue by arkadius** [lift/framework#1658]
"... provide an aNumber parser - returning an Int if succeeding" fails because "1\n" matches criteria aNumber but doesn't match regex expression "\\p{Nd}+.*". Because without DOTALL "\n" doesn't match ".*"

Link to mailing list discussion: https://groups.google.com/forum/#!topic/liftweb/hHzK9lgXyKs

Pull Request: #1659

**Comment by Shadowfiend** [comment]
Fixed via https://github.com/lift/framework/commit/f12a1d905b6aa79cfe7de6d46648c56861d667ba .
