### ISSUE TITLE
MatchWithoutCurrentValue doesn't work for Menu paths that don't have a * in them.

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1669]
For some reason, if you don't include a * in your SiteMap entry, then MatchWithoutCurrentValue just won't work. So, for example, the following won't currently work as expected:

```scala
    // /product/1 produces product info
    // /product/2 should take us to the home page
    lazy val product = Menu.param[ProductInfo]("product", "Product Detail Page",
      id   => lookup(id),
      info => info.id.toString
      ) / "product" >> MatchWithoutCurrentValue >> FallbackToSearchPage
```

There's probably another codepath somewhere that doesn't check for MatchWithoutCurrentValue before bailing if you don't have a * in the path.

Relevant mailing list post [here](https://groups.google.com/d/msg/liftweb/524VF6BD2fs/vkpY4JG-Kh0J).

**Comment by fmpwizard** [comment]
is not having the `*` a valid menu entry?

**Comment by d6y** [comment]
I believe to to be valid without the `*`, based on an example in [Simply Lift](http://simply.liftweb.net/index-3.2.html#toc-Subsection-3.2.7).

**Comment by farmdawgnation** [comment]
Yeah, I also think it's valid, tbh.

**Comment by Shadowfiend** [comment]
The * is (mostly) about where to find the template + where to have placeholders when you've got a multi-param path, but it's optional when you have a single-parameter path if you want the template named the same as the path itself, I believe.

**Comment by fmpwizard** [comment]
always something new to learn, I somehow got used to always including the `*`, even if at the end of the path

**Comment by Shadowfiend** [comment]
I actually do the same :)
