### ISSUE TITLE
NullPointerException in LiftRules:913 when no "parallel"-attribute exists

### ISSUE THREAD

**Issue by andreak** [lift/framework#1671]
In master, version: a21dfa04cef89ab7380c77a09cce53f18865c5d0

Line 913 in LiftRules looks like this
```
912:          val decodedMetaData = pairsToMetaData(encodedArguments.flatMap(_.roboSplit("[;&]")))
913:          if (decodedMetaData("parallel").headOption == Some(Text("true"))) {
```
The definition of MetaData.apply is:

```
  /**
   * Gets value of unqualified (unprefixed) attribute with given key, null if not found
   *
   * @param  key
   * @return value as Seq[Node] if key is found, null otherwise
   */
  def apply(key: String): Seq[Node]
```
Which makes line 913 throw NPE when the attribute="parallel" is not present.

Should be re-written to:
decodedMetaData.get("parallel").headOption

**Comment by Shadowfiend** [comment]
I'm going to go ahead and fix this directly on master rather than going through a PR.

**Comment by fmpwizard** [comment]
:+1:

**Comment by fmpwizard** [comment]
@Shadowfiend would you also fix that one bind bug, where we missed the `s` ? (unless you already did it)

**Comment by andreak** [comment]
He he, just created it: #1672

**Comment by Shadowfiend** [comment]
:thumbsup: will double-check then merge in that case :)

**Comment by Shadowfiend** [comment]
Just to clarify here, this only happened if there were attributes and one of them was not `parallel`?

**Comment by andreak** [comment]
This happened when having markup like:
<div data-lift="surround?with=origo-page">
<div data-lift="bind-at?name=main-content">

Basically all data-lift without the "parallel"-attribute, as sin ```data-lift="surround?with=origo-page;parallel=false"```

**Comment by Shadowfiend** [comment]
Got it, thanks!

@fmpwizard If you point me to the issue number for the bind bug, I'll have a look and get it fixed today.
