### ISSUE TITLE
Lift-json and the dreaded U+2028 character: to escape or not?

### ISSUE THREAD

**Issue by rmat0n** [lift/framework#1676]
From this [thread](https://groups.google.com/d/topic/liftweb/X_u8FoJ2j88/discussion)

Bug (matt): 

> We ran into an interesting issue on our servers tonight, involving the dreaded u\2028 character. After some research, I learned something new: There are some characters that are valid javascript but not valid json, including U+2028.

> Essentially, someone inserted some data to our db with one of these characters, and once we send this down as json (a JObject), the client throws an 'Unexpected Token ILLEGAL' error. As the above link describes, this is character is not valid json.

> ow, I could easily escape these characters on my end, but I wonder if it isn't a better idea to have lift-json handle this case. It would avoid a lot of potential complications, methinks. Antonio recommended a potential solution being to have a toggle on the implicit formats value, but I would go so far as to say, since 'lift-json' handles json, it should *always* escape these characters since they are invalid json.

Solutions (antonio):

> (1) make the user do their own escaping
> (2) bake it in so u+202[89] are always escaped by lift-json
> (3) insert some sort of toggle that allows us to enable this escaping, so that it is disabled by default when lift-json is just dealing in plain JSON.

> I'm okay with the formats solution, or, because this is a fairly specific case, could we just have an extra parameter to render in an overload to avoid API changes and roll this in now rather than later? Mostly I'm keeping in mind the fact that for Lift, as a web framework, there are two core/critical consumers of JSON: other JSON libraries, and JavaScript. Thus, I think we should make sure that JS is a well-considered consumer as soon as possible, though I'm fine with avoiding inefficiencies (i.e., longer encodings) for non-JS consumers.

> I should mention, according to this StackOverflow question, it looks like these are the characters that need JS escaping:

> \u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff

**Comment by farmdawgnation** [comment]
Why was this bug closed?

**Comment by rmat0n** [comment]
By mistake :innocent:
