### ISSUE TITLE
Menu.item evaluation in AJAX requests

### ISSUE THREAD

**Issue by gvdm** [lift/framework#1695]
https://github.com/lift/framework/blob/master/web/webkit/src/main/scala/net/liftweb/builtin/snippet/Menu.scala#L443

For AJAX requests, there is no such Loc. S.originalRequest.map(_.location) meaning that Menu.item will never be correctly evaluated, S.originalRequest.flatMap(_.location) would probably be better in the snippet. Tim Nelson tested this and it does indeed fix the problem.

Mailing list thread: https://groups.google.com/forum/#!topic/liftweb/z9L8p7gKO64

**Comment by Shadowfiend** [comment]
Please make sure to link to the original mailing list discussion in the future :)

**Comment by gvdm** [comment]
The fix has been done by Tim. He finds the precise issue at https://github.com/lift/framework/blob/master/web/webkit/src/main/scala/net/liftweb/builtin/snippet/Menu.scala#L443

I have yet to see a commit for this, has someone with commit privileges got a moment for this?

**Comment by gvdm** [comment]
Will this make it into 3.0?

**Comment by farmdawgnation** [comment]
Er. Hm. @eltimn What's the status here?

**Comment by eltimn** [comment]
I guess I forgot about this as most of the time I only check tickets that are assigned to me. Sorry about that.

I'll assign it to me and see if I can't get this sorted out. I'll try to look at it soon, so I would hope it makes it into 3.0, but I can't promise anything.
