### ISSUE TITLE
Box model improvement

### ISSUE THREAD

**Issue by 99sono** [lift/framework#1716]
Hi There,

This is not an issue is this an improvement request.
So that you enhance the Full box to support a poll wait mechanism on it - if you dim it pertinent.

something of the sort:

val fullBox.waitForCondition(50ms, 1000trie, myConditionChecker)
      for(i =0; i < 100Tries; i++){
           sleep(50ms)
            // after sleeping  let the condition
           val isMyConditionMet = myConditionCheckFunction
           if(isMyConditionMet)
              return;
           // go for another sleep iteration
        }
   catch threadInterruptedException
        return fallse;

 return false;

Something of the sort.

The point was that after having create a Full box that allows me to set values and read values and that it is thread safe.
Once i need to create a system test where several asynchronous EJB calls are triggered, and I need to be sure they are don computing to move on to other validations, it is convenient to have a box object where I can just wait on for its state to change to something else that my  checker function is waiting for.

My system test thread after it lunches some parallel works can just
FullBox.waitThatValueIsTrue (for reasableAmountOfTime)

And I have a pretty easy to use and powerful shared object where I can easily wait for conditions to be met, making the system test robust to delays.

If you think this is pertinent, please consider the improving the Full box to support acting as a shared state between threads where you can easily get some thread to wait upon for a condition to be met.

My kindest regards,
And thank you for your consideration.

**Comment by dpp** [comment]
First, Lift already has Futures. Overloading Box to make it a Future as well doesn't make sense.

Second, in the future, please follow community procedures for opening tickets: https://www.assembla.com/wiki/show/liftweb/Creating_tickets This includes discussion on the mailing list before opening a ticket on GitHub.

Thanks.

**Comment by 99sono** [comment]
Sure,  java also gives you "Futures".

And that is fine, just as long as you can create your own thread pool to run a process that then returns you a future.

Except we are not talking about the same thing right?
When you get a future out of a Thread - and you synchronize your wait on it - that is it, now you wait until that thread is done.

Here we are talking about a shared state.
How do you know which thread is going to bring that state into the condition you are interested in first?
Actually you don't...

More,
When you are on a JEE 6 container, for example - and just because and cal an asychronous EJB you do not get a future out of it. JEE 7 is a different story.


Ultimately, the point is, a Future you use, when the thread model of the framework you're on top of gives you that level of service.

A shared state is a universal concept and so is thread safety.
If you do not think there is added value - fine.
I humbly disagree.

**Comment by farmdawgnation** [comment]
@99sono No, David means that Lift itself provides a future implementation. I'd love to help you figure out how to use it if you need some help.

However, I will have to ask that you jump on the mailing list and start a discussion there. Our community policy is to answer questions like this on our mailing list where the entire community can participate instead of on GitHub issues, where you're more likey to just get feedback from the Committers. (And we're often busy and not quick to respond.)

The mailing list is here: https://groups.google.com/forum/#!forum/liftweb

**Comment by farmdawgnation** [comment]
And to avoid confusion (and to prevent accidental further conversation here) I think I'm going to lock this thread. :-) Cheers!
