### ISSUE TITLE
Avoiding in-lining of Msgs fade and effect scripts 

### ISSUE THREAD

**Issue by karma4u101** [lift/framework#1738]
Prior to lift 3.0 we used a in-lining tail script function in Msgs to append a in-line script to the page for fade and effect scripts. 
With the introduction of Lift's CSP securityRules and the introduction of lift's page script a better solution would be to utilize lift's page script. 
In #1737 I changed the in-lining behaviour to instead append the effect and fade scripts to Lift's page script.

**Comment by Shadowfiend** [comment]
All done!
