### ISSUE TITLE
Inline-JS may break non-HTML5 standard attributes

### ISSUE THREAD

**Issue by fixundfertig123** [lift/framework#1740]
Hi everyone,

Refering to thread
https://groups.google.com/forum/#!topic/liftweb/QOeq-mMFmc0

The inline-js approach causes some headache when using it together with libraries like Angular-xeditable (http://vitalets.github.io/angular-xeditable/), which provides editable elements. The following example shows the problem, where the actual scripts onaftersave & onbeforesave are never called since.

**Original HTML code embedded by 'data-lift="embed?what=html':**
`<span editable-text="list.name" buttons="yes" onbeforesave="XXXXXXXX(list, $data)" onaftersave="YYYYYYYYYY(list)">{{list.name || 'n.a.' }}</span>`

**Resulting HTML code by using 3.0-M3 (works fine):**
`<span editable-text="list.name" buttons="yes" onbeforesave="XXXXXXXX(list, $data)" onaftersave="YYYYYYYYYY(list)" class="ng-scope ng-binding editable editable-click">Dummy</span>`

**Resulting HTML code by using 3.0-M6 (NOT WORKING):**
`<span editable-text="list.name" buttons="yes" id="lift-event-js-F398556110367JMN31O" class="ng-scope ng-binding editable editable-click">Dummy</span>`

Since this breaks the usability of my site, is there a way to disable inline-js by a code-fragement?

Cheers and thanks,

Fritz

**Comment by fixundfertig123** [comment]
Hi,

I forgot to 
Antonio

**Comment by fixundfertig123** [comment]
Sorry, 

mistakenly closed the issue by pressing the wrong button.

I wanted to add a possible solution by Shadowfriend:
- not touching attributes that are non-HTML5. 
- probably add a way to globally disable event attribute extraction.

Cheers Fritz

**Comment by Shadowfiend** [comment]
:heart: thanks. No worries about the accidental close, we've all been there :)

**Comment by fixundfertig123** [comment]
Hi,

good news. I have been so tired that I did forget to test your suggestion of a "data-" prefix, simply because it was not listed in the specs of Angular-xeditable. So close yet so far :-)

It now works for me and I suggested to authors of Angular-xeditable to update theirs specs to be conform to HTML5. Although my problem is solved I do not know whether this is still an issue to others?!?!?!?

Thanks and cheers,

Fritz

**Comment by Shadowfiend** [comment]
Wait, so does Angular-xeditable work *without modification* with a `data-` prefix?

**Comment by fixundfertig123** [comment]
yes, it does work. At least my current testings does not give other indications.

**Comment by Shadowfiend** [comment]
Okay, I'm going to drop this from the M7 milestone and target it at 3.1 given this info… We'll see if it comes out as something more critical after M7 goes out.

**Comment by fixundfertig123** [comment]
Sound very reasonable! Thank you very much for your help!

**Comment by Shadowfiend** [comment]
We ended up adding this after all and defaulting extraction to off for the final Lift 3 release. You can turn it back on using `LiftRules.extractInlineJavaScript = true`.
