### ISSUE TITLE
lift-json issues with deeply nested tuples including Scala primitive types

### ISSUE THREAD

**Issue by Shadowfiend** [lift/framework#1757]
``` scala
import net.liftweb.common._
import net.liftweb.json.{Extraction, _}
import net.liftweb.util.ControlHelpers._
import org.specs2.mutable.

case class Holder(items: List[(String, Long)])

class ExtractionBugSpec extends Specification {
  "Extraction" should {
    "deserialize List of Tuple with Long" in {
      implicit val formats = DefaultFormats

      val holder = Holder(List(("string", 1L)))
      val serialized = compactRender(Extraction.decompose(holder))
      println(serialized)

      val deserialized = tryo(parse(serialized).extract[Holder])
      deserialized must beLike {
        case Full(holderObj) => ok
        case other => {
          println(other)
          ko
        }
      }
    }
  }
}
```

Result:

```
[info] Extraction should
[error] x deserialize List of Tuple with Long
[error]    'Failure(No usable value for items
[error]    No usable value for _2
[error]    No information known about type,Full(net.liftweb.json.MappingException: No usable value for items
[error]    No usable value for _2
[error]    No information known about type),Empty)' doesn't match the expected pattern ko (ExtractionBugSpec.scala:23)
```

ML thread: https://groups.google.com/d/msg/liftweb/8kTftPP7jyQ/jS6UYHinDAAJ

**Comment by Shadowfiend** [comment]
Some deeper investigation revealed that paranamer or reflection (not sure which yet) is reporting that the `Long` parametrized type is instead a `java.lang.Object`: `scala.collection.immutable.List<scala.Tuple2<java.lang.String, java.lang.Object>>`.

**Comment by andreak** [comment]
Last time i had this issue (but with (Long, String)), I came to the conclusion that a custom serializer is needed for this (after some googleing).

```scala
import net.liftweb.json.CustomSerializer
import net.liftweb.json.JsonAST.{JField, JObject, JString}

class LongStringTupleSerializer extends CustomSerializer[(Long, String)](format => ( {
	case JObject(List(JField(k, JString(v)))) => (k.toLong, v)
}, {
	case (l: Long, t: String) => JObject(List(JField(l.toString, JString(t))))
}))
```

Usage:
```scala
implicit val formats = DefaultFormats.lossless ++ JodaTimeSerializers.all + new JsonBoxSerializer + new LongStringTupleSerializer
```

**Comment by Shadowfiend** [comment]
Handy workaround! Did you happen to look into fixing it at the `lift-json` level at the time or not?

**Comment by Shadowfiend** [comment]
Ironically I just realized 1768 was linked to this bug, but 1768 not only doesn't fix this bug, it actually pulls the issue further up the chain by making it so we can't handle *any* Scala primitive types at *any* level :(

Sounds like this bug is what one might call The Worst™.

**Comment by farmdawgnation** [comment]
> Ironically I just realized 1768 was linked to this bug, but 1768 not only doesn't fix this bug, it actually pulls the issue further up the chain by making it so we can't handle any Scala primitive types at any level :(

Just now seeing this. I don't think 1768 made this any worse, did it? But I do think that it's near impossible to handle Scala primitive types with our current implementation. :/ I think this is probably going to be forced to be a wont fix with an eye twoard eventually incorporating the new json extractor, yeah?

**Comment by Shadowfiend** [comment]
Can't remember for sure, but this was about deeply nested tuples, implying top-level ones maybe worked, so perhaps that's what I was getting at.

**Comment by farmdawgnation** [comment]
Ah, yeah, I think that's always been the case. Top level primitives correctly get passed through scalap for type identification. Tuples in parameterized type positions do not, despite my best efforts to make them do so.

**Comment by Shadowfiend** [comment]
Got it. Might be that this didn't change then.

**Comment by farmdawgnation** [comment]
I'm not sure what our policy here should be, but after having spent some time trying to fix this in previous pull requests, I think we consider this a `WONTFIX`. The right solution, imo, is to invest effort in the next generation extractor. Recommend we remove this from 3.2 milestones at the very least since it seems unlikely we'll get it done for 3.2.

**Comment by Shadowfiend** [comment]
I'm cool with that.
