### ISSUE TITLE
Props.whereToLook does not work in 3.0-M8

### ISSUE THREAD

**Issue by serioga** [lift/framework#1776]
There is a change between 3.0-M6 and 3.0-M8 which broke `whereToLook` functionality of `Props`.

The var `providers` in https://github.com/lift/framework/blob/master/core/util/src/main/scala/net/liftweb/util/Props.scala#L397 force to initialize lazy val `props` during initialization of the object `Props`. As result it is not possible to reassign `whereToLook` before initialization of `props`.

This bug is critical for us.

**Comment by joescii** [comment]
Thanks for bringing this to our attention. However per the [Ticket and Pull Request Guidelines](https://github.com/lift/framework/blob/master/CONTRIBUTING.md#ticket-and-pull-request-guidelines) we ask that all issues be first discussed on the [Lift mailing list](https://groups.google.com/forum/#!forum/liftweb).  Please discuss there and we will reopen this issue if needed.

**Comment by fmpwizard** [comment]
reopening as some of us talked about fixing this before RC1

**Comment by Shadowfiend** [comment]
Incidentally, I have a fix for this and a couple of other tiny nits for RC1. Will open a PR tonight! :)

**Comment by fmpwizard** [comment]
awesome!

**Comment by Shadowfiend** [comment]
Incidentally, for us Americans, I dub this the Independence Issue.

**Comment by Shadowfiend** [comment]
Should be fixed in the snapshot!
