### ISSUE TITLE
Implement caching for FullTypeHints

### ISSUE THREAD

**Issue by Shadowfiend** [lift/framework#1777]
`FullTypeHints` in lift-json does a classloader lookup whenever
it tries to instantiate a type, to look the class up based on its
fully-qualified name. Unfortunately, classloader `loadClass` is
a blocking, synchronized action, which can cause serious thread
contention in high load scenarios.

We added a `ConcurrentHashMap` cache of FQNs to `Class`
objects at Elemica to a drop-in replacement class and saw
significant improvements. We should move this into Lift proper.

**Comment by farmdawgnation** [comment]
:+1:

**Comment by farmdawgnation** [comment]
Oh I could have used a reaction if I wasn't mobile.

**Comment by Shadowfiend** [comment]
`FastFullTypeHints` implementation for reference, will try to get this folded in soon:

```scala
case class FastFullTypeHints(hints: List[Class[_]]) extends TypeHints {

  private val hintsToClass: concurrent.Map[String, Class[_]] =
    new ConcurrentHashMap[String, Class[_]]().asScala ++= hints.map(clazz => hintFor(clazz) -> clazz)

  override def hintFor(clazz: Class[_]): String = clazz.getName

  override def classFor(hint: String): Option[Class[_]] =
    hintsToClass.get(hint).orElse {
      val clazz = Thread.currentThread.getContextClassLoader.loadClass(hint)
      hintsToClass.putIfAbsent(hint, clazz).orElse(Some(clazz))
    }
}
```
