### ISSUE TITLE
lift-json serializes NaN and Infinity doubles (invalidly)

### ISSUE THREAD

**Issue by Shadowfiend** [lift/framework#1780]
NaN and Infinity should be serialized to null rather than to their
string representations.

**Comment by farmdawgnation** [comment]
Derrrrrrrp.

**Comment by Shadowfiend** [comment]
Should just be a matter of adding a couple of cases to [this bit of `bufRender`](https://github.com/lift/framework/blob/master/core/json/src/main/scala/net/liftweb/json/JsonAST.scala#L949) to match `JDouble(Double.NegativeInfinity | Double.PositiveInfinity | Double.NaN)` and serialize that to `null`, as well as add specs to check for this behavior.

**Comment by Shadowfiend** [comment]
Still interested in doing this, but… This is potentially a breaking change. Currently lift-json's output can result in invalid JSON. But for folks who are feeding JSON directly into JavaScript, they may be relying on the current functionality.

Going to see about opening a list thread on this, perhaps on Monday.

**Comment by Shadowfiend** [comment]
[Posted the question on what the best path forward is on the list](https://groups.google.com/d/msg/liftweb/7p9CNfClhhM/GaQy3HqDAwAJ).
