### ISSUE TITLE
Call Box.openOrThrowException parameter by name

### ISSUE THREAD

**Issue by serioga** [lift/framework#1781]
**Suggestion to the `Box` API:** make  `openOrThrowException` parameter called by name instead of by value. This will allow to avoid calculation of the “justification” expression for full box.

https://github.com/lift/framework/blob/master/core/common/src/main/scala/net/liftweb/common/Box.scala#L421

**Comment by farmdawgnation** [comment]
Hi @serioga - thanks for the contribution. I like this idea. Per our contributing guidelines, can you start a thread on the [mailing list](http://groups.google.com/forum/#!forum/liftweb) to open the topic for a bit of debate?

I'll close this issue in the interim. After there's some consensus from the community on the mailing list we can reopen it.

**Comment by serioga** [comment]
> can you start a thread on the mailing list to open the topic for a bit of debate?

https://groups.google.com/d/topic/liftweb/vS-FKXMSmrw/discussion
