### ISSUE TITLE
VCardParser (in lift-utils) unable to parse iOS-generated VCards

### ISSUE THREAD

**Issue by themillhousegroup** [lift/framework#1790]
Discussion in this thread:

https://groups.google.com/forum/#!topic/liftweb/70HfjO8XWHk

There is a working (one-line-changed, plus tests) solution ready to pull if desired.
https://github.com/themillhousegroup/framework/tree/handle-apple-vcards

**Comment by farmdawgnation** [comment]
Resolved in the linked PR.
