### ISSUE TITLE
buildDeferredFunction, OfflineRequestSnapshot and serverPort as a lazy val.

### ISSUE THREAD

**Issue by Bhashit** [lift/framework#1794]
This is related to the post I made [here, in the Google group](https://groups.google.com/forum/#!topic/liftweb/2CdURDdKigA). I'll repeat the contents here:

I have a piece of code where the snippet just puts a comet on the page, and then the rest of the work is carried out using Futures. When those Futures complete, the results are sent to the page via the comet-actor.

Now, here's the problem I am facing.
1. I am using `LiftSession#buildDeferredFunction` in order to be able to execute my async code in context of the original request. 
2. `buildDeferredFunction` snapshots the current request, along with a lot of other stuff. As a result, an instance of `net.liftweb.http.provider.servlet.OfflineRequestSnapshot` is created. 
3. In this instance, all the details of the original request are stored using vals. However, only the `serverPort` is specifed as a lazy val. This `serverPort` val refers to a `org.eclipse.jetty.server.Request`, which happens to be mutable.
4. Now, in my Future code, when I need to get the `serverPort`, my `OfflineRequestSnapshot` tries to get it by accessing the jetty Request instance which it has a reference to. 
5. However, there seems to be a race-condition and, intermittently, the jetty Request instance gets changed in the middle (Jetty is reusing it?) and the details get lost, including the uri (which is set as a _uri field in that class).

Now, I can of course, get the server-port in the snippet, and pass it to the Future, along with the comet-name. However, it does seem like we could do something about it while creating the snapshot. This is because there could be quite a bit of code that might use this information. For ex. `S.hostAndPath` will refer to it.

@Shadowfiend suggested in that post that we could do something about it without losing the performance benefits.

Thanks.

**Comment by Bhashit** [comment]
@Shadowfiend I can take care of this issue, and submit a PR. P.S. I'm familiar with the contributing guidelines.

**Comment by Shadowfiend** [comment]
Go for it!

**Comment by Shadowfiend** [comment]
Looks like this got all closed and stuff :tada:
