### ISSUE TITLE
lift.js does not allow to get rid of JQuery

### ISSUE THREAD

**Issue by olegstepura** [lift/framework#1797]
When using vanilla js there is still a direct reference to jQuery during initialization in `lift.js`:

```
onDocumentReady: jQuery(document).ready,
```

AFAIK it can be fixed by wrapping a call to jQuery in a function like this:

```
onDocumentReady: function () {
  jQuery(document).ready.apply(jQuery, Array.prototype.slice.call(arguments));
},
```

**Comment by farmdawgnation** [comment]
Hey @olegstepura - thanks for letting us know about this. Did you open a thread on the Mailing List about it already?

**Comment by olegstepura** [comment]
Hi. No, just filled an issue here.

**Comment by farmdawgnation** [comment]
Would you mind posting there as well and providing any additional, relevant background? There are lots of Lift users who don't monitor the repository who might have run across this and might be able to help.

https://groups.google.com/forum/?fromgroups=#!forum/liftweb

**Comment by olegstepura** [comment]
There is only one thread about vanilla js I could find https://groups.google.com/forum/#!msg/liftweb/DNiWnvwq_I8/J5-fxbzdtDQJ

To get into this issue I created `VanillaJsArtifacts` and used it in `Boot`
Actually I'm not searching for help. I know how to fix it, I think I can make a pull request with the fix and maybe with my Vanilla Js Implementation as well. But my Vanilla Js implementation is not properly tested since most of the methods in it are not required in my app and I don't use it. It's kind of a stub required to make use of lift's comet without the need to include jQuery =)

You can review my `VanillaJsArtifacts` here: https://gist.github.com/olegstepura/08ea9e311a4e27f21c3120e8f2c7389c

**Comment by olegstepura** [comment]
For all who Googles for this, here is my current fix of the mentioned issue (warning: es6 syntax):
```javascript
  window.jQuery = () => {
    const noJqueryError = () => console.error('There is no jQuery object. Please review your code.')
    return { ready: () => noJqueryError() }
  }
```
