### ISSUE TITLE
Inline JS replacement in requests without head and body

### ISSUE THREAD

**Issue by pebrc** [lift/framework#1807]
https://groups.google.com/forum/#!topic/liftweb/mHcv9chTN5k

The new inline JS replacement removes event handlers in Ajax requests that use snippets to render HTML but don't return a full HTML page. 

When the HTML content returned does not contain a head and body tag it seems  that the inline JS is replaced but the event handling code is not delivered to the client. 

The onclick events are thereby essentially removed from the nodes. 

Excerpt from LiftMerge:

```
if (!hasHtmlHeadAndBody) {
  val fixedHtml =
    normalizeMergeAndExtractEvents(xhtml, HtmlState(mergeHeadAndTail = false)).nodes //what happens to the js?

  fixedHtml.find {
    case e: Elem => true
    case _ => false
  } getOrElse Text("")
} else { ....
```

**Comment by Shadowfiend** [comment]
As a short-term fix, in #1809 we're adding a `LiftRules.extractInlineJavaScript` toggle to disable inline JS extraction in Lift 3.0. However, I want to try to fix this for Lift 3.1.
