### ISSUE TITLE
markdown: InlineParser ignores overridden Decorator

### ISSUE THREAD

**Issue by bjoernlenz** [lift/framework#1810]
description and example is here:
https://groups.google.com/d/msg/liftweb/73SB56AFNK4/bCtv3A4BCgAJ

Thanks!
Björn

**Comment by Shadowfiend** [comment]
This guy should be pretty easy to knock out I think, just a matter of adding an `override def deco = BlockParsers.this.deco` to [`ListItem`](https://github.com/lift/framework/blob/master/core/markdown/src/main/scala/net/liftweb/markdown/BlockParsers.scala#L180-L200).

**Comment by farmdawgnation** [comment]
This issue was resolved, but somehow not closed!
