### ISSUE TITLE
CanResolveAsync swallows exceptions

### ISSUE THREAD

**Issue by eiennohito** [lift/framework#1818]
CanResolveAsync swallows exceptions or other errors of Futures and do not even output them even to log.

**Comment by eiennohito** [comment]
In `RestHelper.asyncToResponse`, parameter `asyncResolveProvider: CanResolveAsync[AsyncResolvableType, T]` should be `CanResolveAsync[AsyncResolvableType, Box[T]]` and all implementations should adapt to that.

**Comment by Shadowfiend** [comment]
Per the [contribution guidelines](https://github.com/lift/framework/blob/master/CONTRIBUTING.md), we expect an issue to be related to an existing post on the [Lift mailing list](https://groups.google.com/forum/#!forum/liftweb) where someone has indicated that an issue should in fact be opened. Please go ahead and start that thread and we can reopen this issue once it's been confirmed that it's good to go.
