### ISSUE TITLE
net.liftweb.json.XmlExamples failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [lift/framework#1820]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1080/consoleFull and https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1081/consoleFull

failing commit is 79d036703eedf32a27485574ded1bf2805421ead

last green commit 16f61a0c8d3f647188b0978456e47fc18ecc7293

```
[lift-json] [info] XML Examples
[lift-json] [info] 
[lift-json] [info] + Basic conversion example
[lift-json] [info] + Conversion transformation example 1
[lift-json] [info] + Conversion transformation example 2
[lift-json] [info] + Primitive array example
[lift-json] [info] + Lotto example which flattens number arrays into encoded string arrays
[lift-json] [error] x Band example with namespaces
[lift-json] [error]  'JObject(List(JField(b:band,JObject(List(JField(name,JString(The Fall)), JField(genre,JString(rock)), JField(influence,JString()), JField(playlists,JObject(List(JField(playlist,JArray(List(JObject(List(JField(name,JString(hits)), JField(song,JArray(List(JString(Hit the north), JString(Victoria)))))), JObject(List(JField(name,JString(mid 80s)), JField(song,JArray(List(JString(Eat your self fitter), JString(My new house)))))))))))))))))'
[lift-json] [error]  
[lift-json] [error]   is not equal to 
[lift-json] [error]  
[lift-json] [error]  'JObject(List(JField(b:band,JObject(List(JField(name,JString(The Fall)), JField(genre,JString(rock)), JField(influence,JString()), JField(playlists,JObject(List(JField(playlist,JArray(List(JObject(List(JField(name,JString(hits)), JField(song,JArray(List(JString(Hit the north), JString(Victoria)))))), JObject(List(JField(name,JString(mid 80s)), JField(song,JArray(List(JString(Eat your self fitter), JString(My new house)))))))))))))))))' (XmlExamples.scala:80)
[lift-json] [error] Actual:   ...(rock[)), JField(influence,JString()), JField(playlists,JObject(List(JField(playlist,JArray(List(JObject(List]
[lift-json] [error] [(JField(name,JString(hits)), JField(song,JArray(List(JString(Hit the north), JString(Victoria)))))), JObject(List(JField(name,JString(mid 80s)), JField(song,JArray(List(JString(Eat your self fitter), ]
[lift-json] [error] [JString(My new house)))))))))))))))))]
[lift-json] [error] Expected: ...(rock[]
[lift-json] [error] []
[lift-json] [error] []
[lift-json] [info] 
```

in the community build, I will freeze at 16f61a0c8d3f647188b0978456e47fc18ecc7293 for now

**Comment by Shadowfiend** [comment]
Hmmm… Funkalicious. Particularly since the two things in the example are in fact equal, and [this passed our CI build](https://travis-ci.org/lift/framework/builds/183137334#L2460). Perhaps there's an odd interaction with 2.12... Will try that angle when I get a chance if no one picks it up first.

**Comment by SethTisue** [comment]
I have a test run going at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1082/consoleFull to confirm that freezing at the previous commit makes the problem go away.

the community build is on scala-xml 1.0.6 these days, not sure if that might make a difference, I see you're still on 1.0.5

if you want to try against the latest 2.12.x nightly build of Scala to see if there's actually some 2.12 change that tickled this, see http://stackoverflow.com/a/40622879/86485 for instructions

**Comment by Shadowfiend** [comment]
:thumbsup: appreciate the pointers!

**Comment by Shadowfiend** [comment]
(Notably, this may well be on us---this started failing immediately after we merged some changes to the JSON parser. Only weird thing to look at is that it worked fine in our continuous build but failed in the community one, so may be something concurrency-related.)

**Comment by SethTisue** [comment]
(reverting to the older commit made our run go green again)

**Comment by Shadowfiend** [comment]
Believe we should have a fix in #1822; will post here when that is merged.

**Comment by Shadowfiend** [comment]
Whoops, keeping this open until @SethTisue gets a chance to confirm that things are playing nice again.

**Comment by SethTisue** [comment]
test run in progress at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1116/consoleFull

**Comment by SethTisue** [comment]
compile errors, because you're on ScalaCheck 1.13.x now but the community build is still on 1.12.x — that's https://github.com/scala/community-builds/issues/13

for now I will disable compiling/running of tests. once we get the ScalaCheck upgrade done (hopefully in the next few months) we'll attempt to re-enable them

**Comment by Shadowfiend** [comment]
Quick question re: the ScalaCheck issue---I believe we were on ScalaCheck 1.13 on the previous builds, too (since we've been building on 2.12, I believe). Did something change on your end?

**Comment by SethTisue** [comment]
The community build builds everything from source, so only source compatibility matters, not whether the version numbers are the same. I think that before, you declared a dependency on 1.13 (the community build ignores the number) but were using it in a way that was source-compatible with 1.12. There was no issue until you started using 1.13 specific API.

**Comment by Shadowfiend** [comment]
Hmmm… Interesting. Okay, thanks!
