### ISSUE TITLE
Add Optional versions of Mongo Fields

### ISSUE THREAD

**Issue by eltimn** [lift/framework#1826]

**Comment by Bhashit** [comment]
If this isn't already in progress, I could take this up. I sort of created these versions for a project I was working on (of course, this might be different since we'd want to reuse some existing parts, which wasn't possible in my case).

**Comment by eltimn** [comment]
I have not started this, so feel free to give it a go.

**Comment by Bhashit** [comment]
Alright.

**Comment by Bhashit** [comment]
This was very likely closed by PR #1866.

**Comment by eltimn** [comment]
Yes it was. Thanks again.
