### ISSUE TITLE
We need to handle missing requests in buildDeferredFunction

### ISSUE THREAD

**Issue by arigoldx** [lift/framework#1831]
(n.b. the following is copied from [this mailing list thread](https://groups.google.com/forum/#!msg/liftweb/foD9cXlMxSQ/Cw9zU1c6AwAJ)).

We ran across an issue where `S.req` returns a `Req` without a `HTTPRequest` inside. Ergo, when we call `HttpRequest.snapshot` in `Req.snapshot`, we get a NPE. The basic question is what to do with `Req` when you're in a comet context.

To fix this, we modified `currentReq` in both definitions of `buildDeferredFunction` so that they filter out null requests:

`val currentReq = S.request.filter(_.request != null).map(_.snapshot)`

The situation is basically:

 - Someone sends a message to a comet.
 - We try to create a deferred function (in this case, it's for the future-with-session
   helpers that Piotr created) for lazy-loading.
 - The deferred function builder tries to snapshot the current HTTPRequest.
 - That object is null (due to being in a comet context), and things go boom.

**Comment by Shadowfiend** [comment]
@arigoldx Any chance you can put in a PR for this? 😇

**Comment by arigoldx** [comment]
https://github.com/lift/framework/pull/1844?

**Comment by arigoldx** [comment]
Is there some action I should take here? Not really sure what the assignment is for..

**Comment by Shadowfiend** [comment]
I think this was just Matt updating the issue to reflect the fact that you've been working on it.
