### ISSUE TITLE
HTTPProvider.bootlift catch UnavailableException but should not

### ISSUE THREAD

**Issue by fanf** [lift/framework#1843]
**[Mailing List](https://groups.google.com/forum/#!forum/liftweb) thread:** https://groups.google.com/forum/#!topic/liftweb/BHYjE5C-kIk

The HTTPProvider.bootLift method is catching javax.servlet.UnavailableException, which it should not because the exception is here to tell the application server that the servlet failed to boot.

In Lift 2.6.x, it was even worse because the method was catching ALL exceptions, even Errors. 

*How to reproduce*
Throws a javax.servlet.UnavailableException in Lift boot() method. The exception is caught during boot and the log displays a big warning message:
```
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
******** Failed to Boot! Your application may not run properly
[here the exception message]
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
------------------------------------------------------------------
```

*Use case* 
I'm doing a lot of initialization and resource availability checking at bootstrap, and it was natural to put them in Lift boot() method. The UnavailableException was a conventionnal way to tell the web-app server that something went horribly wrong during init and the servlet is  unavailable. Jetty (for ex) will then respond with "error 503: service unavailable" when a query is done to that app. 

*Workaround*
For now, I added a ServletContextListener where I'm doing the init and throw UnavailableException, but it  splits the initialization logic between it and Lift boot() and make the code harder to follow.

**Comment by farmdawgnation** [comment]
Going to aim to handle this for 3.1.0-M3.
