### ISSUE TITLE
Race-condition in asynchronous response handling

### ISSUE THREAD

**Issue by waern** [lift/framework#1848]
**[Mailing List](https://groups.google.com/forum/#!forum/liftweb) thread:** https://groups.google.com/forum/#!topic/liftweb/-Fve3lAyO7M

My client has an application running Lift 3.0.1 and Jetty 9.2.2. They have a problem with requests that "hang" for a very long time before they are completed with empty responses.

I think this could be due to a race-condition in the method handleGenericContinuation of the class LiftServlet. This method (directly and indirectly) calls the suspend and resume methods of the ServletAsyncProvider interface but does not guarantee that suspend is called before resume. As far as I can see, the order of the calls can depend on the scheduling of threads. And indeed, after having inserted debug traces and attaching a debugger to the server I have the impression that the resume method is sometimes called before the suspend method, leading to the hanging requests we're seeing. Please see mailing list thread for more information.

Minor correction to what I wrote in the mailing list thread: I claimed that the NullPointerExceptions we are seeing are thrown from the complete method of the underlying Servlet 3.0 API. This is wrong -- it is thrown when invoking the getResponse method of the AsyncContext interface (in the resume method of Servlet30AsyncProvider, of course). Sorry for the confusion.

**Comment by Shadowfiend** [comment]
May 15th might be a bit tough to hit, so I'll aim to get this in by the RC.
