### ISSUE TITLE
Investigate interoperability between the lift-json AST and scalajsonast.

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1870]
**[Mailing List](https://groups.google.com/forum/#!forum/liftweb) thread:** N/A

The Scala JSON AST has reached a level of stability where we should look at what we can do from our end in terms of AST compatibility. I think it would be particularly helpful if we started with making it possible to convert between the lift-json AST and the Scala JSON AST.

I've done some prior work to this end at: https://github.com/farmdawgnation/liftjson-scalajson-interop

Implementing a converter in the core lift-json library or in a secondary package would immediately make any library that uses lift-json under the hood immediately compatible with any library that uses any other JSON library that can convert to/from the Scala JSON AST.

**Comment by Bhashit** [comment]
This would be awesome. I am working on an app where converting between the two formats is an extremely common operation. And the way we currently do it is pretty inefficient. I have been thinking about doing this on my own for a while. Let me know if I can lend a hand with this somehow.

**Comment by farmdawgnation** [comment]
The work is done, see #1897, they just haven't released 1.0 final yet so I've been hesitant to merge. If they don't get moving and get it finalized we'll have to decide how bad we want it in Lift 3.2 :(

**Comment by farmdawgnation** [comment]
This still never released a 1.0. We'll close this as a won't fix for now and revisit if this ever becomes stable.
