### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: net/liftweb/json/package$

### ISSUE THREAD

**Issue by ererermao** [lift/framework#1872]
#### version
jdk 1.7.0_67-b01
scala 2.10.6 
spark 1.6
lift-json_2.10-2.6.3.jar
lift-json_2.10-2.5.jar
lift-json_2.10-2.5.1.jar

#### problem
```scala 
import net.liftweb.json._

val json = parse(json1)
```
Exception in thread "main" java.lang.NoClassDefFoundError: net/liftweb/json/package$

**Comment by Shadowfiend** [comment]
Per the [contribution guidelines](https://github.com/lift/framework/blob/master/CONTRIBUTING.md), we expect an issue to be related to an existing post on the [Lift mailing list](https://groups.google.com/forum/#!forum/liftweb) where someone has indicated that an issue should in fact be opened. Please go ahead and start that thread and we can reopen this issue once it's been confirmed to be a bug.
