### ISSUE TITLE
Create giter8 template for lift/framework

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1877]
The [Giter8](https://github.com/foundweekends/giter8) project creator is now built into sbt in the form of `sbt new`. As such, we could instruct people who wanted to start a Lift project to invoke `sbt new lift/framework.g8` to generate a new, blank Lift project.

This requires a few small changes to the lift/framework repo, but I think it's a Really Good Idea™.

**Comment by eltimn** [comment]
FYI, I maintain a lift-mongo version that you could fork if you want: https://github.com/eltimn/lift-mongo.g8
