### ISSUE TITLE
Deprecate json-scalaz

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1898]
**[Mailing List](https://groups.google.com/forum/#!forum/liftweb) thread:** https://groups.google.com/d/msg/liftweb/Kxw4jMsLt44/-D4pWnioCAAJ

The `json-scalaz` module, based on scalaz 6, should be deprecated as an entire module and removed in a hypothetical Lift 4 release. Scalaz 6 hasn't been updated in a long time, and it's probably long past time we did this. =)

**Comment by Shadowfiend** [comment]
! I remember doing that lol.
