### ISSUE TITLE
LiftRules.cometCreation is not considered when building comets

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1902]
**[Mailing List](https://groups.google.com/forum/#!forum/liftweb) thread:** https://groups.google.com/d/msg/liftweb/uFp0jxZVe_I/_LFJ51hwCgAJ

The `LiftRules.cometCreation` value is not considered when building comets as of Lift 3.0. This means that if you try to leverage this value for comet creation, it'll just stop working once you've upgraded from 2.6.

This is a regression from Lift 2.6, so we should also patch Lift 3.0 and Lift 3.1.

Assigning to @Shadowfiend for now since he has some familiarity with the issue and seemed willing to tackle it from the exchange on the ML.

**Comment by Shadowfiend** [comment]
Time permitting!

Will try and give this some love this coming week.
