### ISSUE TITLE
Asset root path should be configurable

### ISSUE THREAD

**Issue by heharkon** [lift/framework#1919]
**Mailing List thread:** https://groups.google.com/forum/#!topic/liftweb/-2Mh4D2L-cM

Ticket per conversation with Antonio, agreed that Lift should have configurable path to reach assets, like images etc. 

Currently the framework implementation has for example the lazy-load snippet's default spinner image hard coded and the g8 template projects place them in a different directory. This leads to lazy-loading spinner not working by default, unless the file is moved under the folder where lift expects it to be found.

**Comment by Bhashit** [comment]
Is anybody working on this? This should be a pretty quick PR. Let me know if I should take care of it.

**Comment by heharkon** [comment]
I was planning to do it, but fail to find proper time to get started (and I'm lazy as a bonus). So if you have time, please, go ahead, would be great! :)

**Comment by heharkon** [comment]
Weeeell, maybe I cold have time for this after all. I just got my dev env set up. :) 

What do you think, would LiftRules be good place to configure this thing, with some default value?

LiftRules.assetPath or similar?

**Comment by farmdawgnation** [comment]
Yeah, generally this sort of thing would be configured in LiftRules.

**Comment by Shadowfiend** [comment]
You can put it into the pull request. I personally prefer not to reference issues from commits, as those “links” are no longer valid if the backing tool we use (GitHub) changes.

**Comment by heharkon** [comment]
Can we close this one? It has been merged now.

**Comment by Shadowfiend** [comment]
Good catch :)
