### ISSUE TITLE
Please publish for Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by Sciss** [lift/framework#1955]
https://github.com/dispatch/reboot/issues/210 depends on `net.liftweb#lift-json` to be available for Scala 2.13.0-M5.

**Comment by Shadowfiend** [comment]
We don't generally *publish* builds for Scala milestones, though we sometimes run the builds. Is there a compelling reason we would do this? I don't know that dispatch makes a habit of doing published milestone builds, either.

**Comment by farmdawgnation** [comment]
> code review + merge + snapshot publish.

Just want to re-iterate that we'd be open to this. We actually publish snapshots on each master merge so all we'd need to do is get this building in master.

**Comment by SethTisue** [comment]
I see there's some activity over at https://github.com/lift/framework/pull/1962

**Comment by Shadowfiend** [comment]
This is a great point, and in fact most of the blockers over there are unrelated to lift-json... While we historically haven’t done any per-module releases, given how much time we respectively have, I may look at how complicated it might be to do a manual milestone release or something for lift-json on Scala 2.13. I’ll bring it up on the list; thanks for the reminder/bump!

**Comment by farmdawgnation** [comment]
I wouldn’t be opposed to running the per module releases

**Comment by Marcel-B** [comment]
Is there a version for Scala 2.13 in sight? That would be pretty nice.

**Comment by Shadowfiend** [comment]
The current SNAPSHOT build is built for 2.13 for most (barring certain persistence ones) Lift modules (as of a few days ago).

**Comment by Marcel-B** [comment]
Thank you very much for the quick answer. SBT could load yesterday only under Scala 1.12.x lift-json. Then I saw on https://mvnrepository.com/artifact/net.liftweb/lift-json that only json-lift up to 1.12.x is supported and I thought that this is the problem. But this morning it worked under version 1.13.x. Unfortunately I didn't find out why.

![image](https://user-images.githubusercontent.com/9868657/66732247-6676b100-ee5b-11e9-85aa-814ff0954db8.png)

**Comment by Shadowfiend** [comment]
You'll want to add the snapshot resolver (see [this example](https://www.scala-sbt.org/1.x/docs/Resolvers.html#Maven+resolvers)) and use `3.4.0-SNAPSHOT` as your version. The 3.4 snapshot contains a handful of targeted bug fixes and 2.13 support, so you should be safe to use it. I need to circle up with the other committers to see how we want to handle doing the actual 3.4 release, and if we want to ship it before all modules are building on 2.13.

**Comment by Shadowfiend** [comment]
Folks, the 3.4.0 final release with support for Scala 2.13 on most modules is [now out](https://github.com/lift/framework/releases/tag/3.4.0-release).

We'll keep this issue open a bit longer as we work towards rounding out the remaining modules and including them in subsequent 3.4.x releases.

**Comment by andreak** [comment]
Anyone using lift-jpa? We are:-)
@dchenbecker Are you still around? Want to release a 2.13-version?

**Comment by Shadowfiend** [comment]
We don't have a 3.0 version of lift-jpa, right? I believe @dpp dropped it in an early 3.0 commit (though I can't find any mention of it being dropped beyond that commit).

**Comment by andreak** [comment]
The artifact is:
```
			<dependency>
				<groupId>org.scala-libs</groupId>
				<artifactId>scalajpa_2.12</artifactId>
				<version>1.5</version>
			</dependency>
```
So it's actually never been a part of Lift...

**Comment by Shadowfiend** [comment]
Ah! Lift had a module adding some support for scala-jpa in the 2.x series, which is why I got confused.

Looks like https://github.com/dchenbecker/scalajpa is the repo for that project.

**Comment by farmdawgnation** [comment]
We're building for 2.13 at this point.
