### ISSUE TITLE
Track down usages of lines and convert to linesIterator

### ISSUE THREAD

**Issue by farmdawgnation** [lift/framework#1966]
The issue scala/bug#11125 means that we need to track down usages of `StringOps.lines` and replace it with `linesIterator` in order to be safe.

We discovered this in #1953 while working on the JDK 11 and 12 builds.

**Comment by farmdawgnation** [comment]
I did a full search of the codebase for `.lines` across all `*.scala` files and only find one other area where we seem to invoke a function called `lines`. That is on the `CompleteMenu` object which defines its parts as a variable named `lines`. Specs might have been the only place we've leaned on `StringOps.lines`.

@Shadowfiend you wanna double check me before I close this out?

**Comment by Shadowfiend** [comment]
I'm 👍 here.
