### ISSUE TITLE
CssBind.calculate does not work for Seq

### ISSUE THREAD

**Issue by PyMountain** [lift/framework#1970]
Hello, i'm having trouble while testing Css selectors,
if i have, let's say, the following CssSel:

`val mySelector =  ".class *" #> "my awesome super String" `

the following works:

` mySelector.stringSelector.openOr("") /* Returns ".class"*/ `
` mySelector.calculate(NodeSeq.Empty) /* Returns "my awesome super String"*/ `

but if i have the following CssSel:

`val mySeletorWithSeq =  ".class" #> Seq("number" #> 1, ".number" #> 2) `

the following works differently:

` mySeletorWithSeq.stringSelector.openOr("") /* Returns ".class"*/ `
` mySeletorWithSeq.calculate(NodeSeq.Empty) /* Returns an Empty NodeSeq*/ `

What i wanted was to have access to the Seq in the right side of my CssSelector, it really should be easier to acess, just like the left side ("mySelector.stringSelector"), other than having to use the calculate function.

Any tips/teaching on how i can do it?

tons of thanks in advance!
<Lucas Andrade/>

**Comment by Shadowfiend** [comment]
Per the [contribution guidelines](https://github.com/lift/framework/blob/master/CONTRIBUTING.md), we expect an issue to be related to an existing post on the [Lift mailing list](https://groups.google.com/forum/#!forum/liftweb) where someone has indicated that an issue should in fact be opened. Please go ahead and start that thread and we can reopen this issue once it's been confirmed that it's good to go!

**Comment by PyMountain** [comment]
Sorry but currently i'm not able to initiate a thread on the lift mailing list, it says i have limited access to the group (AKA i'm not a menber)

**Comment by Shadowfiend** [comment]
You should still see a New Topic button in the top left of the group:

<img width="629" alt="Screen Shot 2019-08-20 at 14 09 07" src="https://user-images.githubusercontent.com/8245/63372597-6d4ddf80-c354-11e9-8842-9e695c410375.png">

You should also be email to directly email liftweb@googlegroups.com .

Please note that messages from new members require manual review from moderators, so it may take a little bit for your message to appear.

If neither of those is working, please share the email you're trying to post as and we'll see what we can figure out.

**Comment by Shadowfiend** [comment]
Ah! Looks like you figured it out :) Thanks!

**Comment by PyMountain** [comment]
yes i did, thank you very much for the quick answer!
