### ISSUE TITLE
SameSite cookie support for Lift

### ISSUE THREAD

**Issue by csaltos** [lift/framework#1989]
**[Mailing List](https://groups.google.com/g/liftweb/c/VzWNc7PWdIo) thread:**

WHAT ?

This is a kind request for adding SameSite cookies support for Lift

WHY ?

SameSite for cookies was kind of optional years ago but now it has reached solid ground and now is a must for web security. More info at https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Set-Cookie/SameSite

HOW ?

Adding sameSite: Box[String] to net.liftweb.http.provider.HttpCookie and it's correspondent value generation at response time

**Comment by Shadowfiend** [comment]
I haven't redone this investigation, but this turned out to be rather complicated in at least some scenarios [last time we looked into it](https://groups.google.com/g/liftweb/c/bKFoFctcY8k/m/KerBmz-xAQAJ). Cc @farmdawgnation who did that investigation at the time.

**Comment by farmdawgnation** [comment]
Added in #1990
